spring:
  config:
    import: "optional:configserver:http://team3-lsc-configserver-service:80/"
  rabbitmq:
    host: rabbitmq.group1-team3
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://team3-lsc-eurekaserver-service:80/eureka/